services:
  - type: web
    name: bonequest-rag
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/main.py
    envVars:
      - key: GROQ_API_KEY
        sync: false